function sparseHistogram(results, bins)
% Plots histograms of sparse matrix S from results (generated by run_RPCA)
%{
This is useful for determining the distribution of pixel values in the
 RPCA-generated sparse matrix, and is how we decided to threshold on one
 standard deviation

Input: 
 - rpcaResults
 - [OPTIONAL] bins
Output: N/A

Joshua Beard
C: 11/21/16
E: 11/21/16
%}
if(nargin < 2)
    S_nonZero = cell(results.setSize,1);
    for(q = 1:results.setSize)
        temp = results.S(:,q);
        temp = (temp(temp ~= 0));
        S_nonZero{q} = temp(:);
        %stdDevNZ(q) = std(temp);
        figure;
        histogram(S_nonZero{q});
    end
else
    S_nonZero = cell(results.setSize,1);
    for(q = 1:results.setSize)
        temp = results.S(:,q);
        temp = (temp(temp ~= 0));
        S_nonZero{q} = temp(:);
        figure;
        histogram(S_nonZero{q});
    end
end
    